'use strict';
(() => {
const D=window.GAIT_CODEBASES, $=id=>document.getElementById(id);
if(!D)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={available_claim:'Stated as available',future_promise:'Promised release',resource_only:'Resource link / statement only',no_explicit_claim_found:'No explicit claim found'};
const q=new URLSearchParams(location.search), years=D.annualClaims.map(r=>String(r.year));
const S={year:years.includes(q.get('codeyear'))?q.get('codeyear'):'',status:['claim',...Object.keys(labels)].includes(q.get('codestatus'))?q.get('codestatus'):'',query:q.get('codeq')||'',page:0,date:D.history.length-1};
const size=20, totalClaims=D.annualClaims.reduce((n,r)=>n+r.claim_count,0);
function save(){const p=new URLSearchParams(location.search);for(const [k,v] of Object.entries({codeyear:S.year,codestatus:S.status,codeq:S.query})){if(v)p.set(k,v);else p.delete(k);}history.replaceState(null,'',location.pathname+'?'+p+location.hash);}
function selected(){const query=S.query.trim().toLowerCase();return D.records.filter(r=>(!S.year||r.year===Number(S.year))&&(!S.status||(S.status==='claim'?['available_claim','future_promise'].includes(r.status):r.status===S.status))&&(!query||`${r.title} ${r.method} ${r.venue}`.toLowerCase().includes(query))).sort((a,b)=>b.year-a.year||a.title.localeCompare(b.title));}
function source(r){return /^https:\/\//i.test(r.sourceUrl)?`<a href="${esc(r.sourceUrl)}" target="_blank" rel="noopener noreferrer">Source publication ↗</a>`:'';}
const chart={left:45,right:480,top:18,bottom:230,width:500,height:260,max:Math.ceil(Math.max(...D.history.map(d=>d.cumulative))/400)*400};
const x=i=>chart.left+i/(D.history.length-1)*(chart.right-chart.left), y=n=>chart.bottom-n/chart.max*(chart.bottom-chart.top);
function historySVG(){
 const points=D.history.map((d,i)=>`${x(i).toFixed(2)},${y(d.cumulative).toFixed(2)}`).join(' '), last=D.history.length-1;
 const ticks=Array.from({length:chart.max/400+1},(_,i)=>i*400);
 return `<svg class="code-history-svg" viewBox="0 0 ${chart.width} ${chart.height}" role="img" aria-labelledby="code-history-title code-history-desc"><title id="code-history-title">OpenGait cumulative recorded stars</title><desc id="code-history-desc">Reconstructed from GitHub aggregate history. Use the date slider below to inspect daily values.</desc>
 ${ticks.map(n=>`<line class="code-history-grid" x1="${chart.left}" y1="${y(n)}" x2="${chart.right}" y2="${y(n)}"/><text class="code-history-axis" x="36" y="${y(n)+4}" text-anchor="end">${n.toLocaleString('en-US')}</text>`).join('')}
 <polygon class="code-history-area" points="${chart.left},${chart.bottom} ${points} ${chart.right},${chart.bottom}"/><polyline class="code-history-line" points="${points}"/>
 ${D.history.map((d,i)=>d.date.endsWith('-01-01')?`<text class="code-history-axis" x="${x(i)}" y="250" text-anchor="middle">${d.date.slice(0,4)}</text>`:'').join('')}
 <line id="code-guide" class="code-history-guide" x1="${x(last)}" x2="${x(last)}" y1="${chart.top}" y2="${chart.bottom}"/><circle id="code-point" cx="${x(last)}" cy="${y(D.history[last].cumulative)}" r="4" fill="#337eae"/></svg>`;
}
function inspectDate(){const d=D.history[S.date];$('code-history-output').textContent=`${d.date} · ${d.cumulative.toLocaleString('en-US')} stars`;$('code-history-range').setAttribute('aria-valuetext',`${d.date}, ${d.cumulative} cumulative recorded stars`);$('code-guide').setAttribute('x1',x(S.date));$('code-guide').setAttribute('x2',x(S.date));$('code-point').setAttribute('cx',x(S.date));$('code-point').setAttribute('cy',y(d.cumulative));}
function rows(){
 const all=selected(), pages=Math.max(1,Math.ceil(all.length/size));S.page=Math.min(S.page,pages-1);
 const shown=all.slice(S.page*size,(S.page+1)*size);
 $('code-results-count').textContent=`${all.length} of ${D.records.length} publications${all.length?` · showing ${S.page*size+1}–${S.page*size+shown.length}`:''}`;
 $('code-audit-rows').innerHTML=shown.length?shown.map(r=>`<tr><td><button class="inline-button code-paper" data-code-paper="${esc(r.paperId)}">${esc(r.title)}</button><small>${esc(r.method)} · ${esc(r.venue)} ${r.year}</small></td><td><span class="code-status ${r.status}">${labels[r.status]}</span></td><td><details><summary>Read audit note${r.evidence?` · PDF p. ${r.evidence.page}`:''}</summary><p>${esc(r.decision)}</p>${r.evidence?`<p>${esc(r.evidence.description)} Page numbers refer to the inspected PDF.</p>`:''}${source(r)}</details></td></tr>`).join(''):'<tr><td colspan="3">No matching records. Try another year, status, or search.</td></tr>';
 $('code-page-label').textContent=`Page ${S.page+1} of ${pages}`;$('code-prev').disabled=S.page===0;$('code-next').disabled=S.page===pages-1;
 document.querySelectorAll('[data-code-paper]').forEach(b=>b.addEventListener('click',()=>window.GAIT_LIBRARY?.openPaper(b.dataset.codePaper)));
 document.querySelectorAll('[data-code-year]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.codeYear===S.year)));
 $('code-year-filter').value=S.year;$('code-status-filter').value=S.status;save();
}
function render(){
 const max=Math.max(...D.repositories.map(r=>r.stars)), opengait=D.repositories.find(r=>r.repository==='ShiqiYu/OpenGait');
 $('view-codebases').innerHTML=`<div class="section-intro"><div><p class="eyebrow">PUBLIC CODEBASES / SEC. III-C</p><h2 id="codebases-title">Code & openness<span class="title-dot">.</span></h2><p>Explore selected gait repositories, OpenGait’s star history, and code-release statements in the survey’s fixed 2020–2025 collection.</p></div></div>
 <div class="code-links"><a href="./assets/public-codebases-statistics.pdf" download>Single-column figure · PDF ↓</a><a href="./codebases.json" download>Source data · JSON ↓</a><a href="https://github.com/ChaoFan996/gait-survey/blob/main/docs/codebases.md">Counting rules ↗</a></div>
 <p class="code-source">GitHub snapshot: ${esc(D.meta.updated)} · Publication audit: ${esc(D.meta.claimAuditDate)} · ${esc(D.meta.snapshotId)}</p>
 <div class="code-summary"><div><strong>${D.repositories.length}</strong><span>Selected public repositories</span></div><div><strong>${opengait.stars.toLocaleString('en-US')}</strong><span>OpenGait stars at retrieval</span></div><div><strong>${totalClaims} / ${D.records.length}</strong><span>Explicit code-release claims · ${(totalClaims/D.records.length*100).toFixed(1)}%</span></div></div>
 <div class="code-cards"><div class="chart-panel"><div class="chart-heading"><div><h3>Repository snapshot</h3><p>GitHub stars · select a repository to visit its code</p></div></div><div class="code-repos">${D.repositories.map(r=>`<a class="code-repo" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer"><span class="code-repo-name">${esc(r.repository.split('/')[1])}<small>${esc(r.role)}</small></span><span class="code-repo-track" aria-hidden="true"><span class="code-repo-fill" style="width:${r.stars/max*100}%"></span></span><span class="code-repo-count">${r.stars.toLocaleString('en-US')}</span></a>`).join('')}</div><p class="code-source">A selected set spanning reference implementations, frameworks, benchmarks, and a system demonstration. Stars indicate attention; this is not a ranking of recognition accuracy or code quality.</p></div>
 <div class="chart-panel"><div class="chart-heading"><div><h3>OpenGait over time</h3><p>Cumulative recorded stars · reconstructed at retrieval</p></div></div>${historySVG()}<div class="code-inspect"><label for="code-history-range">Inspect a date</label><output id="code-history-output" for="code-history-range"></output></div><input class="code-history-range" id="code-history-range" type="range" min="0" max="${D.history.length-1}" value="${S.date}" step="1"><p class="code-source">${esc(D.meta.historyDefinition)} <a href="${esc(D.meta.historySource)}" target="_blank" rel="noopener noreferrer">GitHub API documentation ↗</a></p></div></div>
 <div class="chart-panel"><div class="chart-heading"><div><h3>Code-release statements by publication year</h3><p>Share of each year’s publications · select a year to filter the records below</p></div></div><div class="code-legend"><span><i class="code-available"></i>Stated as available</span><span><i class="code-promised"></i>Promised release</span></div><div class="code-annual">${D.annualClaims.map(r=>`<button class="code-year" data-code-year="${r.year}" aria-pressed="${S.year===String(r.year)}" aria-label="${r.year}: ${r.available_claim} stated as available, ${r.future_promise} promised release, ${r.n} publications. Filter this year."><span class="code-year-plot"><span class="code-year-percent">${r.claim_percent.toFixed(1)}%</span><span class="code-year-stack"><span class="code-available" style="height:${r.available_claim/r.n*320}px"></span><span class="code-promised" style="height:${r.future_promise/r.n*320}px"></span></span></span><span class="code-year-label">${r.year}</span><span class="code-year-count">${r.claim_count} / ${r.n}</span></button>`).join('')}</div><p class="code-source">Counts below each year show publications with an explicit claim / all publications in that year. The chart always uses the fixed 160-publication collection; filters apply to the records below.</p></div>
 <details class="record-detail"><summary>Scope, definitions, and audit method</summary><p>${esc(D.meta.claimDefinition)}</p><p>${esc(D.meta.yearPolicy)} The collection includes reviews and related studies, as in the dataset and modality statistics.</p><p>${esc(D.meta.auditMethod)} “No explicit claim found” does not mean closed source. These statements describe the inspected PDF versions, not reconstructed submission-time versions.</p><p>${esc(D.meta.auditStatus)}. <a href="https://github.com/ChaoFan996/gait-survey/issues/new">Suggest a correction with a source and page number ↗</a></p></details>
 <div class="chart-heading"><div><h3>Publication records</h3><p id="code-results-count" aria-live="polite"></p></div><button class="download-button" id="code-export">Export selection ↓</button></div>
 <div class="controls code-audit-controls"><label>PUBLICATION YEAR<select id="code-year-filter"><option value="">All years</option>${years.map(v=>`<option value="${v}">${v}</option>`).join('')}</select></label><label>CODE STATEMENT<select id="code-status-filter"><option value="">All records</option><option value="claim">Any explicit claim</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label class="code-search">SEARCH PAPERS<input id="code-search" type="search" placeholder="Title, method, or venue" value="${esc(S.query)}"></label><button class="download-button reset-button" id="code-reset">Reset filters</button></div>
 <div class="table-scroll" role="region" aria-label="Publication code statements" tabindex="0"><table class="evidence-table code-audit-table"><thead><tr><th>Paper</th><th>Statement in paper</th><th>Evidence and interpretation</th></tr></thead><tbody id="code-audit-rows"></tbody></table></div><div class="code-pagination"><button id="code-prev">← Previous</button><span id="code-page-label"></span><button id="code-next">Next →</button></div>`;
 $('code-history-range').addEventListener('input',e=>{S.date=Number(e.target.value);inspectDate();});inspectDate();
 $('code-year-filter').addEventListener('change',e=>{S.year=e.target.value;S.page=0;rows();});
 $('code-status-filter').addEventListener('change',e=>{S.status=e.target.value;S.page=0;rows();});
 $('code-search').addEventListener('input',e=>{S.query=e.target.value;S.page=0;rows();});
 $('code-reset').addEventListener('click',()=>{S.year='';S.status='';S.query='';S.page=0;$('code-search').value='';rows();});
 document.querySelectorAll('[data-code-year]').forEach(b=>b.addEventListener('click',()=>{S.year=S.year===b.dataset.codeYear?'':b.dataset.codeYear;S.page=0;rows();}));
 $('code-prev').addEventListener('click',()=>{S.page--;rows();});$('code-next').addEventListener('click',()=>{S.page++;rows();});
 $('code-export').addEventListener('click',()=>{const payload={meta:D.meta,filters:{year:S.year,status:S.status,query:S.query},records:selected()};const u=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='gait-code-claims.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
 rows();
}
window.GAIT_CODEBASES_UI={render};
if(new URLSearchParams(location.search).get('view')==='codebases')render();
})();
