'use strict';
(() => {
const D=window.GAIT_COMPANION, $=id=>document.getElementById(id);
if(!D)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'—':Number(n).toFixed(2).replace(/(\.\d)0$/,'$1');
const percent=(n,total)=>total?(100*n/total).toFixed(1)+'%':'—';
const url=s=>/^https?:\/\//i.test(s||'')?s:'';
const sourceLink=s=>url(s.url)?`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.venue)} ${esc(s.year)} ↗</a>`:`${esc(s.venue)} ${esc(s.year)}`;
const palette=['#1745a3','#789aca','#e58652','#f1b58a','#476f69','#79a59a','#a0aabb','#c8d0dd','#b29dbf','#677a92','#dfaf9e'];
const major=['CASIA-B','OU-MVLP','Gait3D','GREW','BRIAR','SUSTech1K','CCPG'];
const qs=new URLSearchParams(location.search);
const B={domain:qs.get('domain')==='cross'?'cross':'within',target:qs.get('target')||'CCGR-Mini',metric:qs.get('metric')||'R1',train:qs.get('train')||'CCPG',input:qs.get('input')||'',source:qs.get('source')||''};
const S={kind:['datasets','modalities','resources'].includes(qs.get('stats'))?qs.get('stats'):'datasets',year:qs.get('statyear')||'',venue:qs.get('statvenue')||'',selection:null};
function saveParams(obj){const q=new URLSearchParams(location.search);for(const [k,v] of Object.entries(obj)){if(v)q.set(k,v);else q.delete(k);}try{history.replaceState(null,'',location.pathname+'?'+q+location.hash);}catch{}}
function showView(view){
 if(!['library','benchmarks','statistics','map','codebases'].includes(view))view='library';
 for(const name of ['library','benchmarks','statistics','map','codebases']){$('view-'+name).hidden=name!==view;const b=document.querySelector(`[data-view="${name}"]`);if(name===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}
 saveParams({view:view==='library'?'':view});
 if(view==='map')window.GAIT_MAP_UI?.render();if(view==='codebases')window.GAIT_CODEBASES_UI?.render();if(view==='benchmarks')renderBench();if(view==='statistics')renderStats();if(view==='library')window.dispatchEvent(new Event('resize'));
}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('library-scope').innerHTML=`The catalogue retains ${window.GAIT_DATA.papers.length} references. Word-cloud and publication-year statistics use the <strong>${D.meta.recordCount}-publication, 2020–2025 collection</strong> from the specified venues. <button class="inline-button" id="view-scope">View scope and membership ↗</button>`;
$('view-scope').addEventListener('click',()=>showView('statistics'));
document.querySelector('.timeline-note').innerHTML='Counts use the same venue-restricted collection as Statistics.<br><span>2026 references are browseable, outside the frozen counts.</span>';
function optionList(values,value,label){return (label?`<option value="">${esc(label)}</option>`:'')+values.map(v=>`<option value="${esc(v)}"${v===value?' selected':''}>${esc(v)}</option>`).join('');}
function options(label,id,values,value,all){return `<label>${label}<select id="${id}">${optionList(values,value,all)}</select></label>`;}
function inputGroup(r){if(r.input.includes('+'))return 'Mixed inputs';if(r.input==='R')return 'RGB';if(['D','PC'].includes(r.input))return 'LiDAR / geometry';if(r.input==='K')return 'Skeleton';return 'Silhouette';}
function baseResults(){return D.results.filter(r=>r.domain===B.domain&&(B.domain==='within'||r.train===B.train));}
function selectRows(){
 let rows=baseResults().filter(r=>r.target===B.target&&(!B.source||r.source.key===B.source));
 if(B.domain==='within'&&B.target==='CCGR-Mini'){
  const map=new Map();for(const r of rows){const k=r.method+'|'+r.configuration;if(!map.has(k)||(r.metrics.R1??-1)>(map.get(k).metrics.R1??-1))map.set(k,r);}rows=[...map.values()];
 }
 return rows.filter(r=>!B.input||inputGroup(r)===B.input).sort((a,b)=>(b.metrics[B.metric]??-1)-(a.metrics[B.metric]??-1)||a.method.localeCompare(b.method));
}
function renderBench(){
 const trains=[...new Set(D.results.filter(r=>r.domain==='cross').map(r=>r.train))];
 if(B.domain==='cross'&&!trains.includes(B.train))B.train=trains[0];
 let base=baseResults(), targets=[...new Set(base.map(r=>r.target))];
 if(!targets.includes(B.target))B.target=targets[0];
 const allTarget=base.filter(r=>r.target===B.target), metrics=[...new Set(allTarget.flatMap(r=>Object.keys(r.metrics)))];
 if(!metrics.includes(B.metric))B.metric=metrics[0];
 const sources=[...new Map(allTarget.map(r=>[r.source.key,r.source])).values()];
 if(!sources.some(s=>s.key===B.source))B.source=B.domain==='cross'?(sources.find(s=>s.key==='ye2025biggergait')||sources[0])?.key||'':'';
 if(B.domain==='cross'){const selectedMetrics=[...new Set(allTarget.filter(r=>r.source.key===B.source).flatMap(r=>Object.keys(r.metrics)))];metrics.splice(0,metrics.length,...selectedMetrics);if(!metrics.includes(B.metric))B.metric=metrics[0];}
 const rows=selectRows(),available=rows.filter(r=>r.metrics[B.metric]!=null), protocol=B.domain==='cross'?(rows[0]?.protocol||'Direct evaluation after gait training on the selected source dataset.'):D.benchmarks[B.target]?.protocol||'';
 $('view-benchmarks').innerHTML=`<div class="section-intro"><div><p class="eyebrow">TABLE III & FIGURE 5 / REPORTED PERFORMANCE</p><h2 id="benchmark-title">Benchmark explorer<span class="title-dot">.</span></h2><p>Compare reported results within a dataset and protocol. Follow each score to its source and read the training resources alongside the ranking.</p></div><a class="small-link" href="./companion.json" download>Download evidence ↓</a></div>
 <div class="segmented" aria-label="Evaluation setting"><button data-domain="within" aria-pressed="${B.domain==='within'}">Within-domain · Table III</button><button data-domain="cross" aria-pressed="${B.domain==='cross'}">Cross-domain · Fig. 5</button></div>
 <div class="controls">${B.domain==='cross'?options('GAIT TRAINING SOURCE','bench-train',trains,B.train):''}${options('TEST BENCHMARK','bench-target',targets,B.target)}${options('METRIC / CONDITION','bench-metric',metrics,B.metric)}${options('INPUT','bench-input',['Silhouette','RGB','Skeleton','Mixed inputs','LiDAR / geometry'],B.input,'All inputs')}<label>RESULT SOURCE<select id="bench-source">${B.domain==='within'?'<option value="">All imported sources</option>':''}${sources.map(s=>`<option value="${esc(s.key)}"${B.source===s.key?' selected':''}>${esc(s.venue)} ${s.year} · ${esc(s.key)}</option>`).join('')}</select></label></div>
 <p class="evidence-note"><strong>${esc(B.domain==='within'?B.target+' → '+B.target:B.train+' → '+B.target)}.</strong> ${esc(protocol)} ${B.domain==='cross'?'Source-only gait transfer, grouped by reporting paper. R1 denotes the source-reported rank-1 score; condition means are not substituted. CASIA-B and CASIA-B* retain the names used by each source.':''} Rankings cover the imported representative results; inputs and pretraining differ across methods.</p>
 <div class="chart-panel"><div class="chart-heading"><div><h3>${esc(B.target)} · ${esc(B.metric)}</h3><p>${available.length} reported scores · higher is better · click a bar for the complete record</p></div><span class="pill">${B.domain==='within'?'WITHIN DOMAIN':'CROSS DOMAIN'} · %</span></div>
 <div class="rank-axis" aria-hidden="true"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div><div class="rank-list">${available.length?available.map((r,i)=>{const value=r.metrics[B.metric],rank=available.findIndex(x=>x.metrics[B.metric]===value)+1;return `<button class="rank-row" data-result="${r.id}" aria-label="${esc(r.method)}: ${fmt(value)} percent. Show result details"><span class="rank-index">${String(rank).padStart(2,'0')}</span><span class="rank-name">${esc(r.method)}<small>${esc(r.input)} · ${r.year}</small></span><span class="rank-track"><span class="rank-fill" style="display:block;width:${value}%"></span></span><span class="rank-value">${fmt(value)}</span></button>`;}).join(''):'<div class="empty-chart">No reported scores for this selection. Try another input or source.</div>'}</div></div>
 ${B.domain==='within'&&B.target==='CCGR-Mini'?'<p class="evidence-note"><strong>Selection rule.</strong> Choose the highest R1 per listed method configuration among the imported sources, then retain every accompanying metric from that same record. A missing mAP or mINP remains missing. The 27.0 / 24.9 / 9.7 GaitBase record comes from GaitMax Table 2; the alternative 21.1 record is retained in the source history.</p>':''}
 <div class="chart-heading"><div><h3>Scores and provenance</h3><p>Percentages; — means unreported, never zero.</p></div><button class="download-button" id="download-results">Export this selection ↓</button></div>
 <div class="table-scroll"><table class="evidence-table"><thead><tr><th>Method / input</th>${metrics.map(m=>`<th>${esc(m)} (%)</th>`).join('')}<th>Configuration & training resources</th><th>Result source</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="inline-button" data-result="${r.id}">${esc(r.method)}</button><small>${r.year} · ${esc(r.input)}</small></td>${metrics.map(m=>`<td class="numeric">${fmt(r.metrics[m])}</td>`).join('')}<td>${esc(r.configuration)}<small>${esc(r.resources)}</small></td><td>${sourceLink(r.source)}<small>${esc(r.origin)}</small></td></tr>`).join('')}</tbody></table></div>
 ${B.domain==='cross'?crossMatrices():''}
 <details class="record-detail"><summary>How to read these comparisons</summary><p>${esc(D.meta.benchmarkPolicy)}</p><p>The venue list constrains literature statistics. Benchmark evidence follows Table III and Figure 5, so a cited result source such as BiggerGait (NeurIPS) remains available without entering the statistical corpus. S = silhouette; K = skeleton coordinates or maps; R = RGB; P = parsing; F = optical flow; D = LiDAR-derived depth; PC = point cloud. Gait-training source does not describe all external visual pretraining.</p></details>`;
 document.querySelectorAll('[data-domain]').forEach(b=>b.addEventListener('click',()=>{B.domain=b.dataset.domain;B.source='';renderBench();}));
 for(const k of ['train','target','metric','input','source'])$('bench-'+k)?.addEventListener('change',e=>{B[k]=e.target.value;renderBench();});
 document.querySelectorAll('[data-result]').forEach(b=>b.addEventListener('click',()=>openResult(b.dataset.result)));
 $('download-results').addEventListener('click',()=>downloadCSV('gait-results.csv',[['method','year','input','gait_training_source','target','configuration',...metrics,'result_source','source_url','resources'],...rows.map(r=>[r.method,r.year,r.input,r.train,r.target,r.configuration,...metrics.map(m=>r.metrics[m]??''),r.source.key,r.source.url,r.resources])]));
 saveParams({domain:B.domain,target:B.target,metric:B.metric,train:B.domain==='cross'?B.train:'',source:B.source,input:B.input});
}
function crossMatrices(){
 const base=D.results.filter(r=>r.domain==='cross'&&r.train===B.train&&r.source.key===B.source&&(!B.input||inputGroup(r)===B.input));
 const columns=[...new Map(base.flatMap(r=>Object.keys(r.metrics).map(k=>[r.target+'|'+k,[r.target,k]]))).values()];
 const groups=[...new Map(base.map(r=>[r.method+'|'+r.configuration,r])).values()];
 const cell=(row,t,k)=>base.find(r=>r.method===row.method&&r.configuration===row.configuration&&r.target===t)?.metrics[k];
 return `<h3 class="aux-heading">Transfer matrix · trained on ${esc(B.train)}</h3><p class="legend-note">${esc(B.source)} · shared 0–100% scale. All target conditions reported by this source for the selected training source and input filter. <a href="./assets/cross-domain-transfer.pdf" download>Download survey Fig. 5 (PDF) ↓</a></p><div class="table-scroll"><table class="evidence-table"><thead><tr><th>Method</th>${columns.map(([t,m])=>`<th>${esc(t)}<br>${esc(m)}</th>`).join('')}</tr></thead><tbody>${groups.map(r=>`<tr><td>${esc(r.method)}<small>${esc(r.configuration)}</small></td>${columns.map(([t,k])=>{const n=cell(r,t,k);return `<td class="numeric"><span class="cell-score" style="background:${n==null?'#f4f6f9':`rgba(23,69,163,${.04+n/300})`}">${fmt(n)}</span></td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;
}
function openResult(id){
 const r=D.results.find(r=>r.id===id);if(!r)return;
 const others=D.results.filter(x=>x.domain===r.domain&&x.method===r.method&&x.target===r.target&&x.train===r.train);
 $('result-details').innerHTML=`<span class="venue-tag">${r.domain==='within'?'Table III':'Figure 5 / extended evidence'} · ${esc(r.train)} → ${esc(r.target)}</span><h2 id="result-title">${esc(r.method)}</h2><p>${esc(r.domain==='cross'?(r.protocol||'Source-only transfer; see the reporting source for evaluation and preprocessing settings.'):D.benchmarks[r.target].protocol)}</p><dl class="detail-metadata"><dt>Input</dt><dd>${esc(r.input)}</dd><dt>Configuration</dt><dd>${esc(r.configuration)}</dd><dt>Resources</dt><dd>${esc(r.resources)}</dd><dt>Metrics (%)</dt><dd>${Object.entries(r.metrics).map(([k,v])=>esc(k)+': '+fmt(v)).join(' · ')}</dd><dt>Source</dt><dd>${sourceLink(r.source)}<br>${esc(r.source.title)}</dd><dt>Transcription</dt><dd>${esc(r.origin)}</dd></dl>${r.note?`<p class="provenance-note">${esc(r.note)}</p>`:''}${others.length>1?`<h3>Imported source records</h3>${others.map(x=>`<p class="provenance-note">${sourceLink(x.source)} · ${Object.entries(x.metrics).map(([k,v])=>esc(k)+': '+fmt(v)).join(' · ')}<br>${esc(x.note||x.origin)}</p>`).join('')}`:''}<p class="provenance-note">Scores are source-reported. A ranked comparison does not control all differences in pretraining, preprocessing or optimization.</p>`;
 $('result-dialog').showModal();
}
const dialog=document.createElement('dialog');dialog.id='result-dialog';dialog.setAttribute('aria-labelledby','result-title');dialog.innerHTML='<div class="dialog-top"><span class="eyebrow">EXPERIMENTAL RECORD</span><button class="close-button" id="close-result" aria-label="Close result details">×</button></div><div id="result-details"></div>';document.body.append(dialog);$('close-result').addEventListener('click',()=>$('result-dialog').close());
function statRows(){return D.records.filter(r=>(!S.year||String(r.year)===S.year)&&(!S.venue||r.venue===S.venue));}
function count(rows,field){const out={};for(const r of rows)for(const v of r[field])out[v]=(out[v]||0)+1;return out;}
function frequencies(counts,total,field){const items=Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));return items.length?items.map(([name,n])=>`<button class="frequency-row" data-stat-field="${field}" data-stat-value="${esc(name)}" aria-label="${esc(name)}: ${n} publications, ${percent(n,total)}. Show papers"><span class="frequency-label">${esc(name)}</span><span class="frequency-track"><span class="frequency-fill" style="display:block;width:${total?100*n/total:0}%"></span></span><span class="frequency-value">${n} · ${percent(n,total)}</span></button>`).join(''):'<div class="empty-chart">No records match these filters.</div>';}
function annual(rows,field,groups){
 const years=[2020,2021,2022,2023,2024,2025];
 const data=years.map(year=>{const subset=rows.filter(r=>r.year===year),c=count(subset,field);return groups.map(g=>g==='Others'?Object.entries(c).filter(([k])=>!groups.includes(k)).reduce((s,[,v])=>s+v,0):c[g]||0);});
 const max=Math.max(1,...data.map(a=>a.reduce((s,n)=>s+n,0)));
 return `<div class="annual-chart" aria-label="Annual recorded uses">${years.map((y,i)=>{const total=data[i].reduce((s,n)=>s+n,0);return `<div class="annual-column"><b>${total}</b><div class="segments" style="height:${total/max*170}px">${data[i].map((n,j)=>`<span style="height:${total?n/total*100:0}%;background:${palette[j]}"><span class="sr-only">${y} ${esc(groups[j])}: ${n}</span><span title="${y} · ${esc(groups[j])}: ${n}"></span></span>`).join('')}</div><span>${y}</span></div>`;}).join('')}</div><div class="legend">${groups.map((g,i)=>`<span><i style="background:${palette[i]}"></i>${esc(g)}</span>`).join('')}</div>`;
}
function renderStats(){
 const rows=statRows(),uses=rows.reduce((s,r)=>s+r.modalities.length,0),multi=rows.filter(r=>r.modalities.length>1).length;
 $('view-statistics').innerHTML=`<div class="section-intro"><div><p class="eyebrow">FIGURES 5 & 6 / TABLE II</p><h2 id="statistics-title">The collection, in context<span class="title-dot">.</span></h2><p>Dataset usage, recorded inputs and benchmark resources, traced to a shared publication list and an explicit venue scope.</p></div><a class="small-link" href="./statistics-membership.csv" download>Download membership ↓</a></div>
 <div class="scope-box"><strong>2020–2025 · ${D.meta.recordCount} publications after scope reconciliation.</strong> The smaller 168-row modality archive defines the starting membership; ${D.meta.exclusionCount} rows are excluded after venue, publication, year and visual-gait checks. Figures 5–6 and Table II in the revised manuscript use this same membership.<details><summary>Venue list, counting rules and exclusions</summary><p><strong>Included venues:</strong> ${D.meta.allowedVenues.join(', ')}.</p><p>${esc(D.meta.selection)} ${esc(D.meta.datasetPolicy)}</p><p>PRL is distinct from PR. Workshops, preprints and NeurIPS are outside this statistical scope. Related references and benchmark-source papers can remain in the library.</p><ul>${D.exclusions.map(r=>`<li>${esc(r.method)} · ${esc(r.archiveVenue)}: ${esc(r.reason)}</li>`).join('')}</ul><p><a href="./data-audit.json" download>Download the reconciliation log ↓</a></p></details></div>
 <div class="segmented" aria-label="Statistical view">${[['datasets','Dataset usage · Fig. 5'],['modalities','Recorded inputs · Fig. 6'],['resources','Resources · Table II']].map(([k,label])=>`<button data-stat-kind="${k}" aria-pressed="${S.kind===k}">${label}</button>`).join('')}</div>
 <div class="controls">${options('PUBLICATION YEAR','stats-year',[2020,2021,2022,2023,2024,2025].map(String),S.year,'All 2020–2025')}${options('VENUE','stats-venue',D.meta.allowedVenues,S.venue,'All specified venues')}<label>EXPORT<button class="download-button" id="download-stats">Filtered records ↓</button></label></div>
 <div class="stat-summary"><div><strong>${rows.length}</strong><span>publications in this selection</span></div><div><strong>${Object.keys(count(rows,'datasets')).length}</strong><span>recorded dataset labels</span></div><div><strong>${uses}</strong><span>modality uses</span></div><div><strong>${percent(multi,rows.length)}</strong><span>with multiple recorded inputs</span></div></div>
 <div id="stat-body">${S.kind==='datasets'?datasetCharts(rows):S.kind==='modalities'?modalityCharts(rows):resourceTable(rows)}</div><div class="stat-selection" id="stat-selection" hidden></div>`;
 document.querySelectorAll('[data-stat-kind]').forEach(b=>b.addEventListener('click',()=>{S.kind=b.dataset.statKind;S.selection=null;renderStats();}));
 for(const k of ['year','venue'])$('stats-'+k).addEventListener('change',e=>{S[k]=e.target.value;S.selection=null;renderStats();});
 $('download-stats').addEventListener('click',()=>downloadCSV('gait-statistics-selection.csv',[['paperId','year','venue','title','datasets','modalities'],...rows.map(r=>[r.paperId,r.year,r.venue,r.title,r.datasets.join('; '),r.modalities.join('; ')])]));
 document.querySelectorAll('[data-stat-field]').forEach(b=>b.addEventListener('click',()=>showMembers(rows.filter(r=>r[b.dataset.statField].includes(b.dataset.statValue)),b.dataset.statValue)));
 document.querySelectorAll('[data-co]').forEach(b=>b.addEventListener('click',()=>{const [a,c]=b.dataset.co.split('|');showMembers(rows.filter(r=>r.datasets.includes(a)&&r.datasets.includes(c)),a===c?a:a+' + '+c);}));
 document.querySelectorAll('[data-combination]').forEach(b=>b.addEventListener('click',()=>{const ds=b.dataset.combination.split('|');showMembers(rows.filter(r=>ds.every(d=>r.datasets.includes(d))),ds.join(' + '));}));
 document.querySelectorAll('[data-modality-year]').forEach(b=>b.addEventListener('click',()=>{const [m,y]=b.dataset.modalityYear.split('|');showMembers(rows.filter(r=>r.modalities.includes(m)&&r.year===Number(y)),m+' · '+y);}));
 $('resource-search')?.addEventListener('input',e=>document.querySelectorAll('[data-resource-row]').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(e.target.value.toLowerCase())));
 saveParams({stats:S.kind,statyear:S.year,statvenue:S.venue});
}
function datasetCharts(rows){
 const counts=count(rows,'datasets'),mainCounts=Object.fromEntries(major.map(k=>[k,counts[k]||0]));
 return `<div class="chart-grid"><div class="chart-panel"><div class="chart-heading"><div><h3>Common evaluation datasets</h3><p>Each bar: publications / ${rows.length} selected publications.</p></div><span class="pill">FIG. 5</span></div>${frequencies(mainCounts,rows.length,'datasets')}<p class="chart-note">One paper can use several datasets. These percentages need not sum to 100%.</p></div><div class="chart-panel"><div class="chart-heading"><div><h3>Dataset use over time</h3><p>Recorded uses; each dataset counted once per publication.</p></div></div>${annual(rows,'datasets',[...major,'Others'])}</div></div>
 <div class="chart-panel" style="margin-top:20px"><div class="chart-heading"><div><h3>Datasets used together</h3><p>Inclusive pairwise co-usage. Diagonal cells show individual dataset counts; click a cell to inspect its papers.</p></div></div><div class="co-grid"><span></span>${major.map(d=>`<span class="col-label">${d}</span>`).join('')}${major.map(a=>`<span class="row-label">${a}</span>${major.map(b=>{const n=rows.filter(r=>r.datasets.includes(a)&&r.datasets.includes(b)).length;return `<button class="co-cell" data-co="${a}|${b}" aria-label="${a} and ${b}: ${n} publications" style="background:rgba(23,69,163,${.03+.46*n/Math.max(1,...Object.values(mainCounts))})">${n}</button>`;}).join('')}`).join('')}</div></div>
 ${combinationChart(rows)}<details class="record-detail"><summary>All recorded dataset labels</summary>${frequencies(counts,rows.length,'datasets')}</details>`;
}
function modalityCharts(rows){
 const counts=count(rows,'modalities');
 return `<div class="chart-grid"><div class="chart-panel"><div class="chart-heading"><div><h3>Recorded representations</h3><p>Publication counts, with per-paper deduplication.</p></div><span class="pill">FIG. 6</span></div>${frequencies(counts,rows.length,'modalities')}</div><div class="chart-panel"><div class="chart-heading"><div><h3>Input use over time</h3><p>Modality uses, including recorded training auxiliaries.</p></div></div>${annual(rows,'modalities',['Silhouette','Skeleton','RGB','Others'])}<p class="chart-note">${esc(D.meta.modalityPolicy)}</p></div></div>
 ${modalityHeatmap(rows)}<h3 class="aux-heading">Single, multiple and unspecified inputs</h3><div class="table-scroll"><table class="evidence-table"><thead><tr><th>Year</th><th>Publications</th><th>Single input</th><th>Multiple inputs</th><th>Unspecified</th><th>Multiple-input share</th></tr></thead><tbody>${[2020,2021,2022,2023,2024,2025].map(y=>{const rr=rows.filter(r=>r.year===y),single=rr.filter(r=>r.modalities.length===1).length,multiple=rr.filter(r=>r.modalities.length>1).length;return `<tr><td>${y}</td><td class="numeric">${rr.length}</td><td class="numeric">${single}</td><td class="numeric">${multiple}</td><td class="numeric">${rr.length-single-multiple}</td><td class="numeric">${percent(multiple,rr.length)}</td></tr>`;}).join('')}</tbody></table></div>`;
}

function topCombinations(rows){
 const counts=new Map();
 for(const r of rows){const present=major.filter(d=>r.datasets.includes(d));for(let bits=1;bits<(1<<present.length);bits++){const ds=present.filter((_,i)=>bits&(1<<i));if(ds.length<2)continue;const key=ds.join('|');counts.set(key,(counts.get(key)||0)+1);}}
 return [...counts].sort((a,b)=>b[1]-a[1]||a[0].split('|').length-b[0].split('|').length||(a[0]<b[0]?-1:a[0]>b[0]?1:0)).slice(0,10);
}
function combinationChart(rows){return `<div class="chart-panel" style="margin-top:20px"><div class="chart-heading"><div><h3>The ten most frequent dataset combinations</h3><p>Figure 5(b) · inclusive combinations of two or more major datasets. Each paper may contribute to several combinations.</p></div></div><div class="co-combinations">${topCombinations(rows).map(([key,n])=>`<button class="combination-row" data-combination="${esc(key)}"><span>${esc(key.split('|').join(' + '))}</span><strong>${n} · ${percent(n,rows.length)}</strong></button>`).join('')||'<p>No multi-dataset combinations in this selection.</p>'}</div></div>`;}
function modalityHeatmap(rows){const groups=['RGB','Point cloud','SMPL / mesh','Optical flow','Parsing','Pose','Event','Depth','DensePose'],years=[2020,2021,2022,2023,2024,2025];return `<h3 class="aux-heading">Less prevalent modalities over time</h3><p class="legend-note">Figure 6(c) · one recorded use per publication and modality. Click a cell to inspect the contributing papers.</p><div class="table-scroll"><table class="evidence-table modality-heatmap"><thead><tr><th>Recorded input</th>${years.map(y=>`<th>${y}</th>`).join('')}</tr></thead><tbody>${groups.map(m=>`<tr><th>${esc(m)}</th>${years.map(y=>{const n=rows.filter(r=>r.year===y&&r.modalities.includes(m)).length;return `<td><button class="heat-cell" data-modality-year="${esc(m)}|${y}" aria-label="${esc(m)} in ${y}: ${n} publications" style="background:rgba(23,100,135,${.03+Math.min(n,10)*.06})">${n}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;}

function resourceTable(rows){
 const c=count(rows,'datasets');
 return `<div class="chart-heading"><div><h3>Dataset resource catalogue</h3><p>Table II descriptions, with fixed-corpus and filtered usage displayed separately.</p></div><input type="search" id="resource-search" class="resource-search" aria-label="Search dataset resources" placeholder="Find a dataset, modality…"></div><div class="table-scroll"><table class="evidence-table"><thead><tr><th>Dataset / reference</th><th>Year</th><th>Identities</th><th>Sequences / duration</th><th>Available inputs</th><th>Environment</th><th>Table II usage<br>Fixed corpus</th><th>Filtered usage<br>This selection</th></tr></thead><tbody>${D.catalogue.map(r=>`<tr data-resource-row><td>${esc(r.dataset)}<small>${sourceLink(r.source)}</small></td><td>${esc(r.year)}</td><td>${esc(r.identities).replace(/\^\{[^}]*\}/g,'')}</td><td>${esc(r.sequences).replace(/\^\{[^}]*\}/g,'')}</td><td>${esc(r.modality).replace(/\^\{[^}]*\}/g,'')}</td><td>${esc(r.environment)}</td><td class="numeric">${r.archivedUsage??'—'}</td><td class="numeric">${r.archivedUsage==null?'—':c[r.statisticsKey||r.dataset]??0}</td></tr>`).join('')}</tbody></table></div><div class="scope-box">${D.meta.catalogueNotes.map(n=>`<p>${esc(n)}</p>`).join('')}<p>Filtered values retain recorded dataset labels; OU-ISIR uses the OU-LP label. Other aliases and derivatives remain separate; — denotes a resource outside the archived recoding, not zero use.</p></div>`;
}
function showMembers(rows,label){
 const host=$('stat-selection');host.hidden=false;host.innerHTML=`<h3>${esc(label)} · ${rows.length} publications</h3><div class="paper-links">${rows.length?rows.map(r=>`<button data-member="${esc(r.paperId)}">${esc(r.title)}<small>${r.venue} ${r.year} · ${esc(r.method)}</small></button>`).join(''):'<p>No matching publications.</p>'}</div>`;host.querySelectorAll('[data-member]').forEach(b=>b.addEventListener('click',()=>window.GAIT_LIBRARY.openPaper(b.dataset.member)));host.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});
}
function downloadCSV(name,rows){const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"',blob=new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500);}
window.GAIT_COMPANION_UI={showView,getBenchmarkState:()=>({...B}),getSelectedResults:()=>selectRows(),getStatisticsState:()=>({...S,count:statRows().length}),getTopCombinations:()=>topCombinations(statRows())};
showView(qs.get('view')||'library');
})();
