'use strict';
(() => {
const M=window.GAIT_MAP,D=window.GAIT_COMPANION,P=window.GAIT_DATA?.papers;
if(!M||!D||!P)return;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dimensions=M.nodes.filter(n=>n.group==='dimension'),outlooks=M.nodes.filter(n=>n.group==='outlook');
const links=new Map(P.map(p=>[p.id,M.links.filter(l=>l.paperId===p.id)]));
const eligible=new Set(D.records.map(r=>r.paperId));
const params=new URLSearchParams(location.search);
const A={query:params.get('mapq')||'',dimension:params.get('dimension')||'',outlook:params.get('outlook')||'',scope:params.get('mapscope')||'linked',year:'',venue:'',page:1};
const has=(id,node)=>links.get(id)?.some(l=>l.nodeId===node);
const current=()=>P.filter(p=>(A.scope==='all'||A.scope==='corpus'&&eligible.has(p.id)||A.scope==='linked'&&links.get(p.id).length)&&(!A.dimension||has(p.id,A.dimension))&&(!A.outlook||has(p.id,A.outlook))&&(!A.year||String(p.year)===A.year)&&(!A.venue||p.venue===A.venue)&&(!A.query||[p.method,p.title,p.motivation,p.idea,p.techniques].join(' ').toLowerCase().includes(A.query.toLowerCase()))).sort((a,b)=>b.year-a.year||(a.method||a.title).localeCompare(b.method||b.title));
const opt=(values,v)=>values.map(([key,label])=>`<option value="${esc(key)}"${v===key?' selected':''}>${esc(label)}</option>`).join('');
function sync(){const q=new URLSearchParams(location.search);for(const [key,val] of Object.entries({mapq:A.query,dimension:A.dimension,outlook:A.outlook,mapscope:A.scope==='linked'?'':A.scope}))val?q.set(key,val):q.delete(key);history.replaceState(null,'',location.pathname+'?'+q);}
function render(){
 if(!dimensions.some(n=>n.id===A.dimension))A.dimension='';if(!outlooks.some(n=>n.id===A.outlook))A.outlook='';if(!['all','linked','corpus'].includes(A.scope))A.scope='linked';
 $('view-map').innerHTML=`<div class="section-intro"><div><p class="eyebrow">SECTIONS IV–VI / CONNECTED READING</p><h2 id="map-title">From methods to open questions<span class="title-dot">.</span></h2><p>Follow a paper across the five methodological dimensions, then explore its place in the survey’s challenges and outlooks.</p></div><a class="small-link" href="./relationships.csv" download>Download relationships ↓</a></div>
 <div class="dimension-cards">${dimensions.map(n=>{const count=D.records.filter(p=>has(p.paperId,n.id)).length;return `<button class="dimension-card${A.dimension===n.id?' active':''}" data-dimension="${n.id}" aria-pressed="${A.dimension===n.id}"><span>${n.section}</span><h3>${esc(n.short)}</h3><strong>${count}<small> / 160</small></strong><p>publications discussed here</p></button>`;}).join('')}</div>
 <p class="chart-note">Counts above and in the connection matrix use the fixed 160-publication collection. The reading map also includes linked foundational, related and 2026 work. One paper can appear in several dimensions.</p>
 <form class="controls map-controls" id="map-filters" role="search"><label class="map-search">METHOD / TOPIC<input type="search" id="map-search" placeholder="Search GaitMax, occlusion, diffusion…" value="${esc(A.query)}"></label><label>DIMENSION<select id="map-dimension">${opt([['','All five dimensions'],...dimensions.map(n=>[n.id,n.short])],A.dimension)}</select></label><label>CHALLENGE / OUTLOOK<select id="map-outlook">${opt([['','All challenges and outlooks'],...outlooks.map(n=>[n.id,n.title])],A.outlook)}</select></label><label>COLLECTION<select id="map-scope">${opt([['linked','Papers linked in the survey'],['corpus','Fixed 160-publication corpus'],['all','All catalogue references']],A.scope)}</select></label><button type="button" class="reset-button" id="map-reset">Reset</button></form>
 <p class="evidence-note">A filled cell links to an explicit discussion in the survey, with the relevant passage and publication. An empty cell means no indexed link in that section. It is not a judgment about the method’s capabilities.</p>
 <div id="map-results"></div>
 <details class="record-detail map-bridges"><summary>Connections from the five dimensions to the outlooks</summary><p>Each cell counts publications from the fixed corpus discussed in both places. Click to browse the shared papers, including newer references outside the statistical snapshot.</p><div class="table-scroll"><table class="evidence-table bridge-table"><thead><tr><th>Dimension</th>${outlooks.map(n=>`<th>${esc(n.title)}</th>`).join('')}</tr></thead><tbody>${dimensions.map(d=>`<tr><th>${esc(d.short)}</th>${outlooks.map(o=>{const count=D.records.filter(p=>has(p.paperId,d.id)&&has(p.paperId,o.id)).length;return `<td><button class="bridge-cell" data-bridge="${d.id}|${o.id}" aria-label="${esc(d.short)} and ${esc(o.title)}: ${count} publications in the fixed corpus">${count}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div></details>
 <div class="chart-heading"><div><p class="eyebrow">TABLE V / RESEARCH AGENDA</p><h3>Challenges and outlooks</h3><p>Open a topic to read its survey discussion and linked publications.</p></div></div><div class="outlook-grid">${outlooks.map(n=>`<button class="outlook-card" data-topic="${n.id}"><span class="eyebrow">SEC. ${n.section}</span><h3>${esc(n.title)}</h3><p>${esc((n.overview||'').slice(0,235))}${n.overview?.length>235?'…':''}</p><span class="small-link">Explore this connection ↗</span></button>`).join('')}</div>
 <details class="record-detail"><summary>How this map is built and updated</summary><p>${esc(M.meta.policy)}</p><p>Links are extracted from the versioned manuscript and resolved to publication records. Additional editorial links carry source evidence and review metadata. Counts remain tied to the same venue-restricted corpus as Figures 5–6.</p><p><a href="./research-map.json" download>Download the map ↓</a> · <a href="https://github.com/ChaoFan996/gait-survey#updating-the-companion" target="_blank" rel="noopener noreferrer">Update workflow ↗</a></p></details>`;
 $('map-filters').addEventListener('submit',e=>e.preventDefault());
 $('map-search').addEventListener('input',e=>{A.query=e.target.value;A.page=1;renderRows();sync();});
 for(const key of ['dimension','outlook','scope'])$('map-'+key).addEventListener('change',e=>{A[key]=e.target.value;A.page=1;render();});
 $('map-reset').addEventListener('click',()=>{Object.assign(A,{query:'',dimension:'',outlook:'',scope:'linked',page:1});render();});
 document.querySelectorAll('[data-dimension]').forEach(b=>b.addEventListener('click',()=>{A.dimension=A.dimension===b.dataset.dimension?'':b.dataset.dimension;A.page=1;render();}));
 document.querySelectorAll('[data-bridge]').forEach(b=>b.addEventListener('click',()=>{[A.dimension,A.outlook]=b.dataset.bridge.split('|');A.scope='linked';A.page=1;render();$('map-filters').scrollIntoView({block:'start'});}));
 document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>openTopic(b.dataset.topic)));
 renderRows();sync();
}
function renderRows(){
 const rows=current();const size=16,total=Math.max(1,Math.ceil(rows.length/size));A.page=Math.min(A.page,total);const start=(A.page-1)*size;
 $('map-results').innerHTML=`<div class="chart-heading"><div><h3>Paper–dimension map</h3><p aria-live="polite">${rows.length} matching references · click a filled cell for its evidence</p></div><button class="download-button" id="export-map">Export selection ↓</button></div><div class="table-scroll"><table class="evidence-table method-map"><thead><tr><th>Method / publication</th>${dimensions.map(n=>`<th>${esc(n.short)}<small>${n.section}</small></th>`).join('')}<th>Challenges & outlooks</th></tr></thead><tbody>${rows.slice(start,start+size).map(p=>`<tr><td><button class="inline-button" data-map-paper="${esc(p.id)}">${esc(p.method||p.title)}</button><small>${esc(p.venue)} ${p.year}${eligible.has(p.id)?' · statistical corpus':''}</small></td>${dimensions.map(n=>`<td class="map-dot-cell">${has(p.id,n.id)?`<button class="map-dot" data-link="${esc(p.id)}|${n.id}" aria-label="${esc(p.method||p.title)}: ${esc(n.title)}">●</button>`:'<span class="unlinked" aria-label="No indexed discussion">—</span>'}</td>`).join('')}<td><div class="map-tags">${outlooks.filter(n=>has(p.id,n.id)).map(n=>`<button data-link="${esc(p.id)}|${n.id}">${esc(n.short)}</button>`).join('')||'<span class="unlinked">No indexed discussion</span>'}</div></td></tr>`).join('')||'<tr><td colspan="7">No references match this combination. Try one dimension or reset the filters.</td></tr>'}</tbody></table></div><div class="pagination"><button id="map-prev" ${A.page===1?'disabled':''}>← Previous</button><span>${rows.length?start+1:0}–${Math.min(start+size,rows.length)} of ${rows.length}</span><button id="map-next" ${A.page===total?'disabled':''}>Next →</button></div>`;
 document.querySelectorAll('[data-map-paper]').forEach(b=>b.addEventListener('click',()=>window.GAIT_LIBRARY.openPaper(b.dataset.mapPaper)));
 document.querySelectorAll('[data-link]').forEach(b=>b.addEventListener('click',()=>{const [p,n]=b.dataset.link.split('|');openEvidence(p,n);}));
 for(const [id,delta] of [['map-prev',-1],['map-next',1]])$(id).addEventListener('click',()=>{A.page+=delta;renderRows();$('map-results').scrollIntoView({block:'start'});});
 $('export-map').addEventListener('click',()=>download(rows));
}
function openEvidence(pid,nid){
 const p=P.find(p=>p.id===pid),n=M.nodes.find(n=>n.id===nid);if(!p||!n)return;
 const es=M.evidence.filter(e=>e.nodeId===nid&&e.paperIds.includes(pid));
 $('map-evidence').innerHTML=`<span class="eyebrow">SEC. ${n.section} / ${esc(n.title)}</span><h2 id="map-evidence-title">${esc(p.method||p.title)}</h2><p>${esc(p.title)} · ${esc(p.venue)} ${p.year}</p>${es.map(e=>`<article class="map-excerpt"><h3>${esc(e.subtopic||n.title)}</h3><blockquote>${esc(e.text)}</blockquote><p class="chart-note">${esc(e.basis)}${e.line?' · manuscript line '+e.line:''}${e.reviewedBy?' · reviewed by '+esc(e.reviewedBy)+' on '+esc(e.reviewedOn):''}</p></article>`).join('')}<div class="detail-links"><button id="map-open-paper">Read paper details</button>${/^https?:\/\//.test(p.url||'')?`<a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Source publication ↗</a>`:''}</div>`;
 $('map-open-paper').addEventListener('click',()=>{$('map-dialog').close();window.GAIT_LIBRARY.openPaper(pid);});$('map-dialog').showModal();
}
function openTopic(nid){const n=M.nodes.find(n=>n.id===nid);if(!n)return;const rows=P.filter(p=>has(p.id,nid));$('map-evidence').innerHTML=`<span class="eyebrow">SEC. ${n.section} / RESEARCH AGENDA</span><h2 id="map-evidence-title">${esc(n.title)}</h2><p>${esc(n.overview)}</p><h3>Publications connected in the survey</h3><div class="paper-links">${rows.map(p=>`<button data-topic-paper="${esc(p.id)}">${esc(p.method||p.title)}<small>${esc(p.title)} · ${esc(p.venue)} ${p.year}</small></button>`).join('')}</div>`;$('map-evidence').querySelectorAll('[data-topic-paper]').forEach(b=>b.addEventListener('click',()=>{$('map-dialog').close();openEvidence(b.dataset.topicPaper,nid);}));$('map-dialog').showModal();}
function download(rows){const quote=s=>'"'+String(s??'').replace(/"/g,'""')+'"';const data=[['paperId','method','year','venue',...M.nodes.map(n=>n.title)],...rows.map(p=>[p.id,p.method||p.title,p.year,p.venue,...M.nodes.map(n=>has(p.id,n.id)?'Linked':'')])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+data.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));a.download='gait-method-map.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
const dialog=document.createElement('dialog');dialog.id='map-dialog';dialog.setAttribute('aria-labelledby','map-evidence-title');dialog.innerHTML='<div class="dialog-top"><span class="eyebrow">RELATIONSHIP EVIDENCE</span><button id="close-map" class="close-button" aria-label="Close relationship evidence">×</button></div><div id="map-evidence"></div>';document.body.append(dialog);$('close-map').addEventListener('click',()=>dialog.close());
window.GAIT_MAP_UI={render,openEvidence,openTopic,openPaper:id=>{A.query=P.find(p=>p.id===id)?.method||P.find(p=>p.id===id)?.title||'';A.dimension='';A.outlook='';A.scope='all';A.page=1;window.GAIT_COMPANION_UI.showView('map');render();},getState:()=>({...A,total:current().length})};
if(new URLSearchParams(location.search).get('view')==='map')render();
})();
